"""
spawner.py — Creates and launches the next generation.

GUARDRAIL: No Silent Cloning.
  The LLM must supply ALL logic .py files for the next generation.
  This spawner does NOT copy parent logic files — it writes only what the LLM generated.
  If any required file is missing, spawn is aborted with a RuntimeError.

Infrastructure files (telemetry.py, lineage_memory.py) and problem_pool.json
are always copied from the project root — they are not logic, so the LLM never
generates them.
"""
import ast
import datetime
import json
import logging
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Dict

from config import Config
from utils import get_next_generation_dir, save_json
from llm_client import LLMClient

logger = logging.getLogger(__name__)

# Files the LLM MUST generate for every offspring — no fallback copies allowed
# Includes the full multi-agent pipeline and all specialist agents
REQUIRED_LOGIC_FILES = [
    # Orchestration
    "main.py",
    "config.py",
    "llm_client.py",
    "task_manager.py",
    "analysis.py",
    "evolution_engine.py",
    "spawner.py",
    # Multi-agent pipeline
    "contracts.py",
    "agent_base.py",
    "pipeline.py",
    # Specialist agents
    "agent_analyst.py",
    "agent_architect.py",
    "agent_coder.py",
    "agent_critic.py",
    "agent_reviser.py",
    "agent_test_writer.py",
    "agent_debugger.py",
    # Clone guard
    "agent_clone_inspector.py",
]

# Infrastructure files copied from project root (not generated by LLM)
INFRA_FILES = ["telemetry.py", "lineage_memory.py", "persist.py"]


def _get_project_root() -> Path:
    """Resolve project root from this file's location."""
    self_dir = Path(__file__).resolve().parent
    parent = self_dir.parent
    if parent.name == "generations":
        return parent.parent
    return self_dir


class Spawner:
    """
    Validates, writes, and launches the next generation.
    All logic files must be provided by the LLM — no silent copying.
    """

    def __init__(self):
        pass

    def _validate(
        self, new_files: Dict[str, str], current_gen_dir: Path = None
    ) -> None:
        """
        Abort if:
          1. Any required logic file is missing.
          2. Any generated file is content-identical to the parent (silent clone detection).
          3. Any generated file fails to compile (ast.parse).

        Guardrail: No Silent Cloning, No Unchecked Spawning.
        """
        # Guard 1: All required files present
        missing = [f for f in REQUIRED_LOGIC_FILES if f not in new_files]
        if missing:
            raise RuntimeError(
                f"LLM did not generate required file(s): {missing}. "
                f"Spawn aborted — offspring must be fully self-generated, not cloned."
            )

        # Guard 2: Content-identity check — no silent clones on CORE logic files.
        # Stable structural files (contracts, base class) are exempt since they
        # rarely change and the per-file generation strategy produces them faithfully.
        CLONE_EXEMPT = {"contracts.py", "agent_base.py", "task_manager.py"}
        if current_gen_dir and current_gen_dir.exists():
            cloned = []
            for fname in REQUIRED_LOGIC_FILES:
                if fname in CLONE_EXEMPT:
                    continue
                parent_path = current_gen_dir / fname
                if parent_path.exists():
                    try:
                        parent_src = parent_path.read_text(encoding="utf-8").strip()
                        child_src = new_files[fname].strip()
                        if parent_src == child_src:
                            cloned.append(fname)
                    except Exception:
                        pass
            if cloned:
                raise RuntimeError(
                    f"LLM produced files IDENTICAL to parent generation: {cloned}. "
                    f"This is a silent clone — spawn aborted. "
                    f"The LLM must design improved logic, not copy parent code."
                )

        # Guard 3: Compile check
        compile_errors = []
        for fname in REQUIRED_LOGIC_FILES:
            content = new_files[fname]
            try:
                ast.parse(content)
            except SyntaxError as e:
                compile_errors.append(f"{fname}: {e}")

        if compile_errors:
            raise RuntimeError(
                f"Compile errors in LLM-generated files:\n"
                + "\n".join(compile_errors)
            )

        logger.info("All required files present, non-identical to parent, and compile-checked.")

    def _inspect_originality(
        self,
        current_gen_dir: Path,
        new_files_content: Dict[str, str],
        llm_client,
    ) -> None:
        """
        Run the Clone Inspector agent for a rich semantic originality assessment.
        This augments (not replaces) the byte-level identity check in _validate().

        If the inspector returns REJECT, spawn is aborted with a descriptive error.
        Near-clone detections are logged as warnings but do not abort spawn
        (the byte-level check is the hard gate; the inspector adds semantic insight).
        """
        try:
            from agent_clone_inspector import CloneInspectorAgent

            # Load parent source
            parent_files: Dict[str, str] = {}
            for fname in REQUIRED_LOGIC_FILES:
                p = current_gen_dir / fname
                if p.exists():
                    try:
                        parent_files[fname] = p.read_text(encoding="utf-8")
                    except Exception:
                        pass

            inspector = CloneInspectorAgent(llm_client)
            report = inspector.run(
                parent_files=parent_files,
                child_files=new_files_content,
                required_files=REQUIRED_LOGIC_FILES,
            )

            logger.info(
                f"[clone_inspector] verdict={report.verdict} "
                f"score={report.originality_score:.0%} "
                f"identical={report.identical_files} "
                f"near_clones={report.near_clone_files}"
            )
            logger.info(f"[clone_inspector] LLM assessment: {report.llm_assessment[:200]}")
            logger.info(f"[clone_inspector] Recommendation: {report.recommendation}")

            # Hard reject — LLM confirmed this is a semantic clone
            if "REJECT" in report.recommendation.upper():
                raise RuntimeError(
                    f"Clone Inspector REJECTED the offspring (semantic clone detected).\n"
                    f"Verdict: {report.verdict}  Score: {report.originality_score:.0%}\n"
                    f"Assessment: {report.llm_assessment}\n"
                    f"Near-clone files: {report.near_clone_files}\n"
                    f"The LLM must produce genuinely improved logic — not reworded copies."
                )

            if report.near_clone_files:
                logger.warning(
                    f"[clone_inspector] Near-clone files detected (spawn proceeding): "
                    f"{report.near_clone_files}"
                )

            # Store report on self so evolution_tracker can log it
            self._originality_report = report

        except ImportError:
            logger.warning("[clone_inspector] agent_clone_inspector not available — skipping semantic check.")
        except RuntimeError:
            raise  # re-raise rejection
        except Exception as e:
            logger.warning(f"[clone_inspector] Inspection failed (non-fatal): {e}")

    def spawn_next_generation(
        self,
        next_gen_number: int,
        current_gen_dir: Path,
        new_config: Config,
        new_files_content: Dict[str, str],
        improvement_log_message: str,
        analysis_report=None,
        task_results=None,
    ) -> Path:
        """
        Write all LLM-generated files to the next generation directory.
        No parent logic files are copied.

        analysis_report and task_results are optional but required for the
        evolution document (EVOLUTION_LOG.md + evolution_log.json).
        """
        self._originality_report = None

        # Guardrail: No Unchecked Spawning + No Silent Cloning
        self._validate(new_files_content, current_gen_dir)

        # Clone Inspector: semantic originality check (two-stage — difflib + LLM)
        try:
            llm_client = LLMClient(new_config.llm_config)
            self._inspect_originality(current_gen_dir, new_files_content, llm_client)
        except RuntimeError:
            raise
        except Exception as e:
            logger.warning(f"Clone inspector setup failed (non-fatal): {e}")

        next_gen_dir = get_next_generation_dir(next_gen_number)

        if next_gen_dir.exists():
            logger.warning(f"{next_gen_dir} already exists — removing.")
            shutil.rmtree(next_gen_dir)
        next_gen_dir.mkdir(parents=True, exist_ok=True)

        # 1. Write all LLM-generated logic files
        for fname, content in new_files_content.items():
            if not fname.endswith(".py"):
                continue
            dest = next_gen_dir / fname
            dest.parent.mkdir(parents=True, exist_ok=True)
            with open(dest, "w", encoding="utf-8") as f:
                f.write(content)
            logger.info(f"  Written (LLM): {fname}")

        # 2. Copy infrastructure files from project root (not logic — LLM never generates these)
        project_root = _get_project_root()
        for infra in INFRA_FILES:
            src = project_root / infra
            if src.exists():
                shutil.copy(src, next_gen_dir / infra)
                logger.info(f"  Copied (infra): {infra}")
            else:
                logger.warning(f"  Infrastructure file not found: {src}")

        # 3. Copy enriched problem pool
        pool_src = project_root / "data" / "fixed_problem_pool.json"
        if not pool_src.exists():
            pool_src = current_gen_dir / "problem_pool.json"
        if pool_src.exists():
            shutil.copy(pool_src, next_gen_dir / "problem_pool.json")
            logger.info("  Copied: problem_pool.json")
        else:
            logger.warning("  problem_pool.json not found — tasks will fail to load.")

        # 4. Write manifest
        new_config.generation_number = next_gen_number
        new_config.timestamp = datetime.datetime.now().isoformat()
        new_config.improvement_log = improvement_log_message
        new_config.parent_pass_rate = getattr(new_config, "parent_pass_rate", None)

        manifest = {
            "GENERATION": next_gen_number,
            "PARENT_PASS_RATE": new_config.parent_pass_rate,
            "PARENT_ERRORS": getattr(new_config, "parent_error_types", {}),
            "IMPROVEMENT_LOG": improvement_log_message,
            "TIMESTAMP": new_config.timestamp,
            "FILES_GENERATED_BY_LLM": [f for f in new_files_content if f.endswith(".py")],
        }
        with open(next_gen_dir / "manifest.json", "w") as f:
            json.dump(manifest, f, indent=4)
        logger.info("  Written: manifest.json")

        logger.info(f"Generation {next_gen_number} spawned at {next_gen_dir}")

        # 5. Write evolution document (non-fatal — don't abort spawn on tracker errors)
        try:
            from evolution_tracker import record_spawn
            current_topology = getattr(new_config, "topology", None)
            # new_config already mutated to next gen — reconstruct parent topology from
            # what was passed in (the parent's topology before evolution)
            parent_topology_dict = {}
            if hasattr(new_config, "_parent_topology"):
                parent_topology_dict = new_config._parent_topology
            child_topology_dict = current_topology.to_dict() if current_topology else {}

            originality = (
                self._originality_report.to_dict()
                if self._originality_report else {}
            )
            record_spawn(
                from_gen=next_gen_number - 1,
                analysis_report=analysis_report,
                task_results=task_results or [],
                improvement_log=improvement_log_message,
                topology_from=parent_topology_dict,
                topology_to=child_topology_dict,
                originality_report=originality,
            )
        except Exception as e:
            logger.warning(f"  evolution_tracker failed (non-fatal): {e}")

        return next_gen_dir

    def launch_next_generation(self, next_gen_dir: Path) -> None:
        """Launch main.py of the next generation as an independent process."""
        main_script = next_gen_dir / "main.py"
        if not main_script.exists():
            raise FileNotFoundError(f"main.py not found in {next_gen_dir}")

        log_file = next_gen_dir / "child_generation.log"
        logger.info(f"Launching {next_gen_dir.name} — output → {log_file}")
        with open(log_file, "w") as outf:
            subprocess.Popen(
                [sys.executable, str(main_script)],
                cwd=next_gen_dir,
                stdout=outf,
                stderr=subprocess.STDOUT,
                close_fds=True,
            )
        logger.info(f"{next_gen_dir.name} launched.")
