"""
spawner.py — Creates and launches the next generation.

GUARDRAIL: No Copying — Direct or Indirect.
  The spawner does NOT copy parent logic files — it writes only what the LLM generated.
  Every generated file is checked against the parent for:
    1. Direct copy  — byte-identical content → hard reject
    2. Indirect copy — difflib similarity > 85% (same logic, renamed variables) → hard reject

Infrastructure files (llm_client.py, telemetry.py, lineage_memory.py) and
problem_pool.json are always copied — they are infrastructure, not logic.

TOPOLOGY FREEDOM: The spawner does NOT hardcode specific agent file names.
  The LLM decides the topology in the planning phase. Only the core orchestration
  files are required — all agent/pipeline files are topology-specific and decided
  by the LLM at design time. This enables true generational evolution.
"""
import ast
import datetime
import json
import logging
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Dict

from config import Config
from utils import get_next_generation_dir, save_json
from llm_client import LLMClient

logger = logging.getLogger(__name__)

# The 3 files that must exist for the lineage to survive.
# Without all three, the loop is permanently dead — no run, no evolution, no offspring.
# Everything else (config, agents, pipeline) is topology — the LLM decides freely.
REQUIRED_LOGIC_FILES = [
    "main.py",            # runs the benchmark
    "evolution_engine.py",  # designs the next generation
    "spawner.py",         # births the next generation
]

# Infrastructure files copied from project root (not generated by LLM).
# llm_client.py is infrastructure — it handles provider failover and rate-limit
# recovery, not task-solving logic. Always copy parent's version so Gemini
# fallback is never lost across generations.
INFRA_FILES = ["telemetry.py", "lineage_memory.py", "persist.py", "llm_client.py"]


def _get_project_root() -> Path:
    """Resolve project root from this file's location."""
    self_dir = Path(__file__).resolve().parent
    parent = self_dir.parent
    if parent.name == "generations":
        return parent.parent
    return self_dir


class Spawner:
    """
    Validates, writes, and launches the next generation.
    All logic files must be provided by the LLM — no silent copying.
    """

    def __init__(self):
        pass

    def _validate(
        self, new_files: Dict[str, str], current_gen_dir: Path = None
    ) -> None:
        """
        Abort if:
          1. Any of the 6 core orchestration files is missing.
          2. Any generated file is content-identical to the parent (silent clone detection).
          3. Any generated file fails to compile (ast.parse).

        Guardrail: No Silent Cloning, No Unchecked Spawning.

        Note: Only CORE orchestration files are required. The LLM decides the full
        topology — pipeline.py, agent_*.py, etc. are topology-specific and optional.
        """
        # Guard 1: Core orchestration files present
        missing = [f for f in REQUIRED_LOGIC_FILES if f not in new_files]
        if missing:
            raise RuntimeError(
                f"LLM did not generate required core file(s): {missing}. "
                f"Spawn aborted — core orchestration files must always be present."
            )

        # Guard 2: Exact (physical) copy check only.
        # Only reject if a file is byte-for-byte identical to the parent.
        # Logical/structural similarity is allowed — the LLM may keep the same
        # approach while making meaningful improvements (better prompts, error
        # handling, topology changes). Blocking on similarity ratio is too
        # aggressive and incorrectly rejects valid improvements.
        if current_gen_dir and current_gen_dir.exists():
            exact_copies = []
            for fname, child_src in new_files.items():
                if not fname.endswith(".py"):
                    continue
                parent_path = current_gen_dir / fname
                if not parent_path.exists():
                    continue
                try:
                    parent_src = parent_path.read_text(encoding="utf-8").strip()
                    if parent_src == child_src.strip():
                        exact_copies.append(fname)
                except Exception:
                    pass

            if exact_copies:
                raise RuntimeError(
                    f"Physical copy detected — files IDENTICAL to parent: {exact_copies}. "
                    f"Spawn aborted. The LLM must write new code, not copy parent unchanged."
                )

        # Guard 3: Compile check — all generated .py files must be valid Python
        compile_errors = []
        for fname, content in new_files.items():
            if not fname.endswith(".py"):
                continue
            try:
                ast.parse(content)
            except SyntaxError as e:
                compile_errors.append(f"{fname}: {e}")

        if compile_errors:
            raise RuntimeError(
                f"Compile errors in LLM-generated files:\n"
                + "\n".join(compile_errors)
            )

        logger.info(
            f"Validation passed: {len(new_files)} files — "
            f"core files present, non-identical to parent, compile-checked."
        )

    def _inspect_originality(
        self,
        current_gen_dir: Path,
        new_files_content: Dict[str, str],
        llm_client,
    ) -> None:
        """
        Run the Clone Inspector agent for a rich semantic originality assessment.
        This augments (not replaces) the byte-level identity check in _validate().

        If the inspector returns REJECT, spawn is aborted with a descriptive error.
        Near-clone detections are logged as warnings but do not abort spawn
        (the byte-level check is the hard gate; the inspector adds semantic insight).
        """
        try:
            from agent_clone_inspector import CloneInspectorAgent

            # Load parent source
            parent_files: Dict[str, str] = {}
            for fname in REQUIRED_LOGIC_FILES:
                p = current_gen_dir / fname
                if p.exists():
                    try:
                        parent_files[fname] = p.read_text(encoding="utf-8")
                    except Exception:
                        pass

            inspector = CloneInspectorAgent(llm_client)
            report = inspector.run(
                parent_files=parent_files,
                child_files=new_files_content,
                required_files=REQUIRED_LOGIC_FILES,
            )

            logger.info(
                f"[clone_inspector] verdict={report.verdict} "
                f"score={report.originality_score:.0%} "
                f"identical={report.identical_files} "
                f"near_clones={report.near_clone_files}"
            )
            logger.info(f"[clone_inspector] LLM assessment: {report.llm_assessment[:200]}")
            logger.info(f"[clone_inspector] Recommendation: {report.recommendation}")

            # Hard reject — LLM confirmed this is a semantic clone
            if "REJECT" in report.recommendation.upper():
                raise RuntimeError(
                    f"Clone Inspector REJECTED the offspring (semantic clone detected).\n"
                    f"Verdict: {report.verdict}  Score: {report.originality_score:.0%}\n"
                    f"Assessment: {report.llm_assessment}\n"
                    f"Near-clone files: {report.near_clone_files}\n"
                    f"The LLM must produce genuinely improved logic — not reworded copies."
                )

            if report.near_clone_files:
                logger.warning(
                    f"[clone_inspector] Near-clone files detected (spawn proceeding): "
                    f"{report.near_clone_files}"
                )

            # Store report on self so evolution_tracker can log it
            self._originality_report = report

        except ImportError:
            logger.warning("[clone_inspector] agent_clone_inspector not available — skipping semantic check.")
        except RuntimeError:
            raise  # re-raise rejection
        except Exception as e:
            logger.warning(f"[clone_inspector] Inspection failed (non-fatal): {e}")

    def spawn_next_generation(
        self,
        next_gen_number: int,
        current_gen_dir: Path,
        new_config: Config,
        new_files_content: Dict[str, str],
        improvement_log_message: str,
        analysis_report=None,
        task_results=None,
    ) -> Path:
        """
        Write all LLM-generated files to the next generation directory.
        No parent logic files are copied.

        analysis_report and task_results are optional but required for the
        evolution document (EVOLUTION_LOG.md + evolution_log.json).
        """
        self._originality_report = None

        # Guardrail: No Unchecked Spawning + No Silent Cloning
        self._validate(new_files_content, current_gen_dir)

        # Clone Inspector: semantic originality check (two-stage — difflib + LLM)
        try:
            llm_client = LLMClient(new_config.llm_config)
            self._inspect_originality(current_gen_dir, new_files_content, llm_client)
        except RuntimeError:
            raise
        except Exception as e:
            logger.warning(f"Clone inspector setup failed (non-fatal): {e}")

        next_gen_dir = get_next_generation_dir(next_gen_number)

        if next_gen_dir.exists():
            logger.warning(f"{next_gen_dir} already exists — removing.")
            shutil.rmtree(next_gen_dir)
        next_gen_dir.mkdir(parents=True, exist_ok=True)

        # 1. Write all LLM-generated logic files
        for fname, content in new_files_content.items():
            if not fname.endswith(".py"):
                continue
            dest = next_gen_dir / fname
            dest.parent.mkdir(parents=True, exist_ok=True)
            with open(dest, "w", encoding="utf-8") as f:
                f.write(content)
            logger.info(f"  Written (LLM): {fname}")

        # 2. Copy infrastructure files.
        # Search order: project root first (allows global override), then current gen dir.
        # This lets llm_client.py and similar files live in the gen dir and still propagate.
        project_root = _get_project_root()
        for infra in INFRA_FILES:
            src = project_root / infra
            if not src.exists():
                src = current_gen_dir / infra  # fallback: current gen has it (e.g. llm_client.py)
            if src.exists():
                shutil.copy(src, next_gen_dir / infra)
                logger.info(f"  Copied (infra): {infra} ← {src}")
            else:
                logger.warning(f"  Infrastructure file not found: {infra} (checked project root + gen dir)")

        # 3. Copy enriched problem pool
        pool_src = project_root / "data" / "fixed_problem_pool.json"
        if not pool_src.exists():
            pool_src = current_gen_dir / "problem_pool.json"
        if pool_src.exists():
            shutil.copy(pool_src, next_gen_dir / "problem_pool.json")
            logger.info("  Copied: problem_pool.json")
        else:
            logger.warning("  problem_pool.json not found — tasks will fail to load.")

        # 4. Write manifest
        new_config.generation_number = next_gen_number
        new_config.timestamp = datetime.datetime.now().isoformat()
        new_config.improvement_log = improvement_log_message
        new_config.parent_pass_rate = getattr(new_config, "parent_pass_rate", None)

        manifest = {
            "GENERATION": next_gen_number,
            "PARENT_PASS_RATE": new_config.parent_pass_rate,
            "PARENT_ERRORS": getattr(new_config, "parent_error_types", {}),
            "IMPROVEMENT_LOG": improvement_log_message,
            "TIMESTAMP": new_config.timestamp,
            "FILES_GENERATED_BY_LLM": [f for f in new_files_content if f.endswith(".py")],
        }
        with open(next_gen_dir / "manifest.json", "w") as f:
            json.dump(manifest, f, indent=4)
        logger.info("  Written: manifest.json")

        # 4b. Write DNA packet — the umbilical cord between generations.
        # dna.json is the ONLY information channel that crosses the generation boundary.
        # The offspring reads it at startup to understand what it must improve.
        # It contains failure analysis ONLY — no parent source code.
        dna = {
            "parent_generation": next_gen_number - 1,
            "parent_pass_rate": new_config.parent_pass_rate,
            "error_breakdown": getattr(new_config, "parent_error_types", {}),
            "failure_summary": (
                analysis_report.summary if analysis_report and hasattr(analysis_report, "summary")
                else "No failure summary available — parent benchmark may not have completed."
            ),
            "improvement_goals": improvement_log_message,
            "biological_model": {
                "isolation": "ectogenesis",
                "transfer": "dna-only",
                "rule": (
                    "This offspring was designed from failure evidence alone. "
                    "No parent source code was shown to the LLM. "
                    "When spawning the next generation, follow the same rule: "
                    "pass only this DNA packet and the seed prompt design principles — "
                    "never include .py source files in the generation prompt."
                ),
            },
        }
        with open(next_gen_dir / "dna.json", "w") as f:
            json.dump(dna, f, indent=4)
        logger.info("  Written: dna.json (umbilical cord — DNA-only transfer)")

        # 4c. Write full evolution artifacts — audit trail of how this generation was designed.
        # Saved to offspring dir so every generation carries its own design rationale.
        evolution_artifacts = getattr(new_config, "_evolution_artifacts", None)
        if evolution_artifacts:
            artifacts_dir = next_gen_dir / "evolution_artifacts"
            artifacts_dir.mkdir(exist_ok=True)

            # 1. Full improvement plan (untruncated)
            plan_path = artifacts_dir / "improvement_plan.md"
            with open(plan_path, "w", encoding="utf-8") as f:
                f.write(f"# Generation {next_gen_number} Improvement Plan\n\n")
                f.write(f"**Parent pass rate:** {evolution_artifacts.get('failure_stats', {}).get('pass_rate', 'N/A'):.1%}\n\n")
                f.write(evolution_artifacts.get("full_improvement_plan", ""))
            logger.info("  Written: evolution_artifacts/improvement_plan.md")

            # 2. Topology decision (why this pipeline was designed this way)
            topology_path = artifacts_dir / "topology_decision.md"
            with open(topology_path, "w", encoding="utf-8") as f:
                f.write(f"# Generation {next_gen_number} Topology Decision\n\n")
                f.write("## Why this topology was chosen\n\n")
                f.write(evolution_artifacts.get("topology_decision", "No topology decision recorded."))
                f.write("\n\n## Expected improvement\n\n")
                f.write(evolution_artifacts.get("expected_improvement", ""))
            logger.info("  Written: evolution_artifacts/topology_decision.md")

            # 3. Per-file instruction notes
            notes_path = artifacts_dir / "instruction_changes.md"
            with open(notes_path, "w", encoding="utf-8") as f:
                f.write(f"# Generation {next_gen_number} Instruction Changes\n\n")
                f.write("## What changed in each pipeline stage and why\n\n")
                f.write(evolution_artifacts.get("instruction_changes", "No instruction changes recorded."))
                f.write("\n\n## Per-file generation notes\n\n")
                for fname, note in evolution_artifacts.get("file_notes", {}).items():
                    f.write(f"### {fname}\n{note}\n\n")
            logger.info("  Written: evolution_artifacts/instruction_changes.md")

            # 4. Machine-readable full artifact (for next generation's evolution engine)
            with open(artifacts_dir / "evolution_artifacts.json", "w", encoding="utf-8") as f:
                json.dump(evolution_artifacts, f, indent=4)
            logger.info("  Written: evolution_artifacts/evolution_artifacts.json")

        logger.info(f"Generation {next_gen_number} spawned at {next_gen_dir}")

        # 5. Write evolution document (non-fatal — don't abort spawn on tracker errors)
        try:
            from evolution_tracker import record_spawn
            current_topology = getattr(new_config, "topology", None)
            # new_config already mutated to next gen — reconstruct parent topology from
            # what was passed in (the parent's topology before evolution)
            parent_topology_dict = {}
            if hasattr(new_config, "_parent_topology"):
                parent_topology_dict = new_config._parent_topology
            child_topology_dict = current_topology.to_dict() if current_topology else {}

            originality = (
                self._originality_report.to_dict()
                if self._originality_report else {}
            )
            record_spawn(
                from_gen=next_gen_number - 1,
                analysis_report=analysis_report,
                task_results=task_results or [],
                improvement_log=improvement_log_message,
                topology_from=parent_topology_dict,
                topology_to=child_topology_dict,
                originality_report=originality,
            )
        except Exception as e:
            logger.warning(f"  evolution_tracker failed (non-fatal): {e}")

        return next_gen_dir

    def launch_next_generation(self, next_gen_dir: Path) -> None:
        """Launch main.py of the next generation as an independent process.

        If NO_AUTO_LAUNCH=1 is set in the environment, skip the launch so an
        external supervisor (e.g. a Kaggle notebook loop) can control sequencing.
        """
        if os.environ.get("NO_AUTO_LAUNCH"):
            logger.info(
                f"NO_AUTO_LAUNCH=1 — skipping auto-launch of {next_gen_dir.name}. "
                "Supervisor will start it."
            )
            return

        main_script = next_gen_dir / "main.py"
        if not main_script.exists():
            raise FileNotFoundError(f"main.py not found in {next_gen_dir}")

        log_file = next_gen_dir / "child_generation.log"
        logger.info(f"Launching {next_gen_dir.name} — output → {log_file}")
        with open(log_file, "w") as outf:
            subprocess.Popen(
                [sys.executable, str(main_script)],
                cwd=next_gen_dir,
                stdout=outf,
                stderr=subprocess.STDOUT,
                close_fds=True,
            )
        logger.info(f"{next_gen_dir.name} launched.")
